### ISSUE TITLE
npm package not working

### ISSUE THREAD

**Issue by ryota-mitarai** [ryota-mitarai/aframe-websurfaces#1]
When you download and locally import the built package (for example, ```import 'websurface.umd.js'```), everything works correctly.

However, if you import the package from npm, using ```import 'aframe-websurfaces'```, it doesn't work and gives an error:

![image](https://user-images.githubusercontent.com/80703263/118883155-ee882c80-b8c2-11eb-8400-97aef4575fc0.png)

I think it gives the error on line 23 in DOMElement.js:
```super(geometry, material);```
and it sounds like it's something to do with transpiling down into ES5, but I'm not sure why it only happens when the files are downloaded from npm.

**Comment by ryota-mitarai** [comment]
fixed in https://github.com/ryota-mitarai/aframe-websurfaces/commit/823a26c5b96ae89418a494ccd1d10b593d843ed3 (release v1.2.0)

I guess it was something to do with the three dependency

**Comment by carlosveny** [comment]
In A-Frame 1.3.0 this error happens again. Any fix?
